# Generated by Django 5.0.2 on 2024-04-03 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255, verbose_name='Detail')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=255, verbose_name='Assignment')),
                ('date', models.DateField(verbose_name='Date')),
                ('location', models.CharField(max_length=255, verbose_name='Location of the Assignment')),
                ('category', models.CharField(choices=[('Live', 'Live'), ('Recording', 'Recording'), ('Other', 'Other')], max_length=20, verbose_name='Category')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Date of Submission')),
                ('agreement', models.BooleanField(default=False, verbose_name='Agreement')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Production Approved', 'Production Approved'), ('Treasurer Approved', 'Treasurer Approved'), ('Technical Approved', 'Technical Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('slug', models.SlugField(default='')),
                ('rejection_reason', models.TextField(blank=True)),
                ('details', models.ManyToManyField(to='equipment.assignmentdetail', verbose_name='Details of the Assignment')),
                ('persons_assigned', models.ManyToManyField(related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Person(s) Assigned')),
                ('requested_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requested_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('task_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.taskassignment')),
            ],
        ),
    ]
