# Generated by Django 5.0.2 on 2024-04-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_assignmentdetail_taskassignment_assignmentequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
