# Generated by Django 5.0.2 on 2024-04-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_taskassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('In Maintenance', 'In Maintenance')], default='Available', max_length=20, verbose_name='Status'),
        ),
    ]
