# Generated by Django 5.0.2 on 2024-06-16 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='amount_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Required'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='current_stage',
            field=models.CharField(choices=[('Production', 'Production'), ('Technical', 'Technical'), ('Treasurer', 'Treasurer'), ('Cashier', 'Cashier')], default='Production', max_length=20),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='persons_required',
            field=models.ManyToManyField(related_name='required_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Person(s) Required'),
        ),
    ]
