# Generated by Django 5.0.2 on 2024-06-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_taskassignment_amount_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='persons_required',
        ),
    ]
