# Generated by Django 5.0.2 on 2024-06-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_taskassignment_cashier_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='amount_required',
        ),
    ]
