# Generated by Django 5.0.2 on 2024-10-15 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_alter_taskassignment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='assistant_treasurer_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assistant_treasurer_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_treasurer_approved_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='technical_manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='technical_manager_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_manager_approved_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
