# Generated by Django 5.0.2 on 2024-10-16 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_taskassignment_assistant_treasurer_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='return_confirmed',
            field=models.BooleanField(default=False, verbose_name='Return Confirmed'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='return_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_returns', to=settings.AUTH_USER_MODEL, verbose_name='Return Confirmed By'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Return Date'),
        ),
        migrations.CreateModel(
            name='TaskAssignmentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('persons_assigned', models.JSONField()),
                ('submission_date', models.DateTimeField()),
                ('equipment_details', models.JSONField()),
                ('status', models.CharField(max_length=50)),
                ('approved_by', models.JSONField()),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_task_assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.taskassignment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
