# Generated by Django 5.0.2 on 2024-10-17 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_taskassignment_return_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='equipment',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date'),
        ),
    ]
