# Generated by Django 5.0.2 on 2024-10-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_remove_equipment_quantity_equipment_registered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignmentarchive',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taskassignmentarchive',
            name='updated_at',
        ),
    ]
