# Generated by Django 5.0.2 on 2024-04-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_and_date', models.DateTimeField()),
                ('program_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('played', 'Played'), ('running', 'Running'), ('next', 'Next'), ('not_played', 'Not Played')], default='not_played', max_length=10)),
                ('is_new', models.CharField(choices=[('new', 'New'), ('repeated', 'Repeated'), ('live', 'Live')], default='new', max_length=10)),
            ],
        ),
    ]
