# Generated by Django 5.0.2 on 2024-03-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0002_remove_myuser_middle_name_alter_myuser_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
