# Generated by Django 5.0.2 on 2024-08-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0005_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
