# Generated by Django 5.0.2 on 2024-08-08 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('working_holiday', models.CharField(choices=[('year', 'Yearly'), ('maternity', 'Maternity'), ('sick', 'Sick')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('my_last_holiday_start', models.DateField()),
                ('my_last_holiday_end', models.DateField()),
                ('current_address', models.TextField()),
                ('description', models.TextField()),
                ('delegatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_delegatee', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
