# Generated by Django 5.0.2 on 2024-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0004_holiday_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='delegatee_approved',
            field=models.BooleanField(default=False),
        ),
    ]
