# Generated by Django 5.0.2 on 2024-08-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0006_overlaydescription_overlay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='description',
        ),
    ]
