# Generated by Django 5.0.2 on 2024-08-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0007_remove_holiday_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='rejected',
        ),
        migrations.AddField(
            model_name='holiday',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='working_holiday',
            field=models.CharField(blank=True, choices=[('year', 'Mwaka'), ('maternity', 'Uzazi'), ('sick', 'Ugonjwa'), ('malipo', 'Bila Malipo')], max_length=10, null=True),
        ),
    ]
