# Generated by Django 5.0.2 on 2024-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0008_remove_holiday_approved_remove_holiday_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='director_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holiday',
            name='production_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holiday',
            name='technical_manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holiday',
            name='treasurer_approved',
            field=models.BooleanField(default=False),
        ),
    ]
