# Generated by Django 5.0.2 on 2024-08-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0010_programcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcount',
            name='program_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
