# Generated by Django 5.0.2 on 2024-08-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0012_alter_programcount_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcount',
            name='program_name',
            field=models.CharField(max_length=255, verbose_name='pro.Program'),
        ),
        migrations.AlterUniqueTogether(
            name='programcount',
            unique_together={('holiday', 'program_name')},
        ),
    ]
