# Generated by Django 5.0.2 on 2024-08-29 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0013_alter_programcount_program_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('place', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reporting_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('approved_by_delegatee', models.BooleanField(default=False)),
                ('approved_by_production', models.BooleanField(default=False)),
                ('approved_by_technical_manager', models.BooleanField(default=False)),
                ('approved_by_treasurer', models.BooleanField(default=False)),
                ('approved_by_director', models.BooleanField(default=False)),
                ('delegatee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegatee', to=settings.AUTH_USER_MODEL)),
                ('duties', models.ManyToManyField(to='vacation.duty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
