# Generated by Django 5.0.2 on 2024-09-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0016_alter_permissionrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Under Review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Under Review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
