# Generated by Django 5.0.2 on 2024-10-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0018_alter_programcount_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='my_tasks',
            field=models.TextField(blank=True, help_text='Comma-separated list of tasks', null=True),
        ),
    ]
