# Generated by Django 5.0.2 on 2024-10-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0021_delete_duty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='assistant_treasurer_approved',
            field=models.BooleanField(default=False),
        ),
    ]
