# Generated by Django 5.0.2 on 2024-10-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0022_holiday_assistant_treasurer_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='marketing_officer_approved',
            field=models.BooleanField(default=False),
        ),
    ]
