# Generated by Django 5.0.2 on 2024-03-29 12:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_numeric', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_words', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('description', models.CharField(default='No description provided', max_length=255)),
                ('total_request', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approved_by_production', models.BooleanField(default=False)),
                ('approved_by_technical_manager', models.BooleanField(default=False)),
                ('approved_by_finance', models.BooleanField(default=False)),
                ('approved_by_treasurer', models.BooleanField(default=False)),
                ('approved_by_cashier', models.BooleanField(default=False)),
                ('wef', models.DateField(blank=True, null=True)),
                ('account_to_charge', models.CharField(blank=True, max_length=100, null=True)),
                ('account_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review')], default='Pending', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='My Item', max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_request', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('financial_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.financialrequest')),
            ],
        ),
    ]
