# Generated by Django 5.0.2 on 2024-03-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrequest',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
