# Generated by Django 5.0.2 on 2024-03-31 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financialrequest_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrequest',
            name='slug',
        ),
    ]
