# Generated by Django 5.0.2 on 2024-03-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_financialrequest_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrequest',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
