# Generated by Django 5.0.2 on 2024-10-10 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_financialrequest_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrequest',
            name='approved_by_assistant_treasurer',
            field=models.ManyToManyField(blank=True, related_name='approved_by_assistant_treasurer', to=settings.AUTH_USER_MODEL),
        ),
    ]
