# Generated by Django 5.0.2 on 2024-10-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_financialrequest_approved_by_assistant_treasurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrequest',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
