# Generated by Django 5.0.2 on 2024-10-18 11:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_financialrequest_date_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRequestArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_numeric', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_words', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('description', models.CharField(default='No description provided', max_length=255)),
                ('total_request', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wef', models.DateField(blank=True, null=True)),
                ('account_to_charge', models.CharField(blank=True, max_length=100, null=True)),
                ('account_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review')], default='Pending', max_length=20)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by_production', models.TextField(blank=True, null=True)),
                ('approved_by_technical_manager', models.TextField(blank=True, null=True)),
                ('approved_by_finance', models.TextField(blank=True, null=True)),
                ('approved_by_treasurer', models.TextField(blank=True, null=True)),
                ('approved_by_cashier', models.TextField(blank=True, null=True)),
                ('approved_by_assistant_treasurer', models.TextField(blank=True, null=True)),
                ('original_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financialrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-archived_at'],
            },
        ),
    ]
