# Generated by Django 5.0.2 on 2024-11-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_financialrequestarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrequest',
            name='rejection_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
